name: cosmic_gnomad_annotation
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - pysam>=0.22.0
  - bcftools=1.21
  - htslib=1.21
  - numpy>=1.21.0
  - pandas>=1.3.0
