name: rna_editing_annotation
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pysam=0.22.0
  - bcftools=1.21
  - tabix=1.21
  - bgzip=1.21
  - psutil=5.9.0
  - pip
  - pip:
    - argparse